apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pizza-deployment
  labels:
    app: pizza-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-api
  template:
    metadata:
      labels:
        app: pizza-api
    spec:
      containers:
      - name: pizza-api
        image: shezcode/pizza-backend:00
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
